[Greeter]
WallpaperPluginId=org.kde.image

[Greeter][Wallpaper][org.kde.image][General]
Image=file:///usr/share/wallpapers/DarkCache/contents/images/Space.jpeg
PreviewImage=file:///usr/share/wallpapers/DarkCache/contents/images/Space.jpeg
